//! Compliance backend implementation for iac-forge.
//!
//! Implements the `Backend` trait to generate InSpec controls (.rb) and
//! RSpec synthesis tests (_spec.rb) from the platform-independent IR.

use iac_forge::backend::{ArtifactKind, Backend, GeneratedArtifact, NamingConvention};
use iac_forge::error::IacForgeError;
use iac_forge::ir::{IacDataSource, IacProvider, IacResource};

use crate::config::ComplianceConfig;
use crate::inspec_gen;
use crate::rspec_gen;

/// Compliance InSpec + RSpec backend.
pub struct ComplianceBackend {
    config: ComplianceConfig,
}

impl ComplianceBackend {
    /// Create a new `ComplianceBackend` with default configuration.
    #[must_use]
    pub fn new() -> Self {
        Self {
            config: ComplianceConfig::default(),
        }
    }

    /// Create a new `ComplianceBackend` with custom configuration.
    #[must_use]
    pub fn with_config(config: ComplianceConfig) -> Self {
        Self { config }
    }
}

impl Default for ComplianceBackend {
    fn default() -> Self {
        Self::new()
    }
}

/// Naming convention for compliance artifacts.
struct ComplianceNaming;

impl NamingConvention for ComplianceNaming {
    fn resource_type_name(&self, resource_name: &str, provider_name: &str) -> String {
        format!("{provider_name}_{resource_name}")
    }

    fn data_source_type_name(&self, ds_name: &str, provider_name: &str) -> String {
        format!("data_{provider_name}_{ds_name}")
    }

    fn file_name(&self, resource_name: &str, kind: &ArtifactKind) -> String {
        match kind {
            ArtifactKind::Test => format!("{resource_name}_spec.rb"),
            _ => format!("{resource_name}.rb"),
        }
    }

    fn field_name(&self, api_name: &str) -> String {
        api_name.replace('-', "_")
    }
}

impl Backend for ComplianceBackend {
    fn platform(&self) -> &str {
        "compliance"
    }

    fn naming(&self) -> &dyn NamingConvention {
        &ComplianceNaming
    }

    fn generate_resource(
        &self,
        resource: &IacResource,
        _provider: &IacProvider,
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        let inspec = inspec_gen::generate_resource_controls(resource, &self.config);
        let rspec = rspec_gen::generate_resource_tests(resource, &self.config);

        Ok(vec![
            GeneratedArtifact {
                path: format!(
                    "profiles/{}/controls/{}.rb",
                    resource.name, resource.name
                ),
                content: inspec,
                kind: ArtifactKind::Test,
            },
            GeneratedArtifact {
                path: format!("spec/compliance/{}_spec.rb", resource.name),
                content: rspec,
                kind: ArtifactKind::Test,
            },
        ])
    }

    fn generate_data_source(
        &self,
        ds: &IacDataSource,
        _provider: &IacProvider,
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        // Data sources get a minimal InSpec existence control.
        let inspec = format!(
            "# frozen_string_literal: true\n# Code generated by compliance-forge. DO NOT EDIT.\n\ncontrol '{name}-existence' do\n  impact 1\n  title '{name} data source must exist'\n  desc 'Verify that the {name} data source is accessible.'\n  tag nist: ['CM-2', 'CM-8']\n\n  describe {name}(name: resource_name) do\n    it {{ should exist }}\n  end\nend\n",
            name = ds.name,
        );

        let rspec = format!(
            "# frozen_string_literal: true\n# Code generated by compliance-forge. DO NOT EDIT.\n\nRSpec.describe '{name}' do\n  let(:synthesized_resource) {{ subject }}\n\n  describe 'existence' do\n    it 'data source {name} should be present' do\n      expect(synthesized_resource).not_to be_nil\n    end\n  end\nend\n",
            name = ds.name,
        );

        Ok(vec![
            GeneratedArtifact {
                path: format!("profiles/{}/controls/{}.rb", ds.name, ds.name),
                content: inspec,
                kind: ArtifactKind::Test,
            },
            GeneratedArtifact {
                path: format!("spec/compliance/{}_spec.rb", ds.name),
                content: rspec,
                kind: ArtifactKind::Test,
            },
        ])
    }

    fn generate_provider(
        &self,
        provider: &IacProvider,
        resources: &[IacResource],
        _data_sources: &[IacDataSource],
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        // Generate an inspec.yml profile manifest for the provider.
        let mut resource_list = String::new();
        for r in resources {
            resource_list.push_str(&format!("#   - {}\n", r.name));
        }

        let yml = format!(
            r#"---
name: {name}-compliance
title: {name} compliance controls
version: {version}
summary: Auto-generated InSpec controls for {name} resources
maintainer: compliance-forge
copyright: compliance-forge
license: MIT
supports:
  - platform: {name}
# Resources:
{resource_list}"#,
            name = provider.name,
            version = provider.version,
        );

        Ok(vec![GeneratedArtifact {
            path: "inspec.yml".to_string(),
            content: yml,
            kind: ArtifactKind::Metadata,
        }])
    }

    fn generate_test(
        &self,
        resource: &IacResource,
        _provider: &IacProvider,
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        // Tests are already generated alongside resources in generate_resource.
        // This method returns an empty vec to avoid duplication.
        // The generate_all override handles proper ordering.
        let _ = resource;
        Ok(vec![])
    }

    fn generate_all(
        &self,
        provider: &IacProvider,
        resources: &[IacResource],
        data_sources: &[IacDataSource],
    ) -> Result<Vec<GeneratedArtifact>, IacForgeError> {
        let mut artifacts = Vec::new();

        for r in resources {
            artifacts.extend(self.generate_resource(r, provider)?);
        }

        for ds in data_sources {
            artifacts.extend(self.generate_data_source(ds, provider)?);
        }

        artifacts.extend(self.generate_provider(provider, resources, data_sources)?);

        Ok(artifacts)
    }

    fn validate_resource(
        &self,
        resource: &IacResource,
        _provider: &IacProvider,
    ) -> Vec<String> {
        let mut errors = Vec::new();
        if resource.attributes.is_empty() {
            errors.push(format!(
                "resource '{}' has no attributes",
                resource.name
            ));
        }
        errors
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use iac_forge::ir::IacType;
    use iac_forge::testing::{
        TestAttributeBuilder, test_data_source, test_provider, test_resource,
        test_resource_with_type,
    };

    fn backend() -> ComplianceBackend {
        ComplianceBackend::new()
    }

    fn provider() -> IacProvider {
        test_provider("akeyless")
    }

    // ---- platform ----

    #[test]
    fn platform_name() {
        assert_eq!(backend().platform(), "compliance");
    }

    // ---- NamingConvention ----

    #[test]
    fn naming_resource_type() {
        let n = ComplianceNaming;
        assert_eq!(
            n.resource_type_name("static_secret", "akeyless"),
            "akeyless_static_secret"
        );
    }

    #[test]
    fn naming_data_source_type() {
        let n = ComplianceNaming;
        assert_eq!(
            n.data_source_type_name("secret", "akeyless"),
            "data_akeyless_secret"
        );
    }

    #[test]
    fn naming_file_name_test() {
        let n = ComplianceNaming;
        assert_eq!(
            n.file_name("static_secret", &ArtifactKind::Test),
            "static_secret_spec.rb"
        );
    }

    #[test]
    fn naming_file_name_other() {
        let n = ComplianceNaming;
        assert_eq!(
            n.file_name("static_secret", &ArtifactKind::Resource),
            "static_secret.rb"
        );
    }

    #[test]
    fn naming_field_name() {
        let n = ComplianceNaming;
        assert_eq!(n.field_name("bound-aws-account-id"), "bound_aws_account_id");
    }

    // ---- generate_resource ----

    #[test]
    fn generate_resource_produces_two_artifacts() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert_eq!(artifacts.len(), 2);
        assert_eq!(artifacts[0].kind, ArtifactKind::Test);
        assert_eq!(artifacts[1].kind, ArtifactKind::Test);
    }

    #[test]
    fn generate_resource_inspec_path() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert_eq!(
            artifacts[0].path,
            "profiles/static_secret/controls/static_secret.rb"
        );
    }

    #[test]
    fn generate_resource_rspec_path() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert_eq!(
            artifacts[1].path,
            "spec/compliance/static_secret_spec.rb"
        );
    }

    #[test]
    fn generate_resource_inspec_has_existence() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("-existence'"));
        assert!(artifacts[0].content.contains("should exist"));
    }

    #[test]
    fn generate_resource_rspec_has_existence() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[1].content.contains("existence"));
        assert!(artifacts[1].content.contains("not_to be_nil"));
    }

    #[test]
    fn generate_resource_inspec_has_required() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("-required-attrs'"));
    }

    #[test]
    fn generate_resource_inspec_has_sensitive() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("-sensitive-protection'"));
    }

    #[test]
    fn generate_resource_inspec_has_immutable() {
        let b = backend();
        let p = provider();
        let r = test_resource("static_secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("-immutable-enforcement'"));
    }

    #[test]
    fn generate_resource_empty_attrs() {
        let b = backend();
        let p = provider();
        let mut r = test_resource("empty");
        r.attributes.clear();

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert_eq!(artifacts.len(), 2);
        // Should still have existence control
        assert!(artifacts[0].content.contains("-existence'"));
    }

    #[test]
    fn generate_resource_with_all_attr_types() {
        let b = backend();
        let p = provider();
        let mut r = test_resource("full");
        r.attributes.push(
            TestAttributeBuilder::new("status", IacType::String)
                .enum_values(vec!["on".into(), "off".into()])
                .build(),
        );
        r.attributes.push(
            TestAttributeBuilder::new("ttl", IacType::Integer)
                .default_value(serde_json::json!(3600))
                .build(),
        );

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        // InSpec should have all 7 control types
        let inspec = &artifacts[0].content;
        assert!(inspec.contains("-existence'"));
        assert!(inspec.contains("-required-attrs'"));
        assert!(inspec.contains("-type-validation'"));
        assert!(inspec.contains("-sensitive-protection'"));
        assert!(inspec.contains("-immutable-enforcement'"));
        assert!(inspec.contains("-enum-validation'"));
        assert!(inspec.contains("-default-verification'"));
    }

    #[test]
    fn generate_resource_with_sensitive_attrs() {
        let b = backend();
        let p = provider();
        let r = test_resource("secret_item");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("sensitive-protection"));
    }

    #[test]
    fn generate_resource_with_immutable_attrs() {
        let b = backend();
        let p = provider();
        let r = test_resource("key_item");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("immutable-enforcement"));
    }

    #[test]
    fn generate_resource_with_enum_attrs() {
        let b = backend();
        let p = provider();
        let mut r = test_resource("enum_item");
        r.attributes.push(
            TestAttributeBuilder::new("mode", IacType::String)
                .enum_values(vec!["read".into(), "write".into()])
                .build(),
        );

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("enum-validation"));
        assert!(artifacts[0].content.contains("'read', 'write'"));
    }

    #[test]
    fn generate_resource_with_default_values() {
        let b = backend();
        let p = provider();
        let mut r = test_resource("default_item");
        r.attributes.push(
            TestAttributeBuilder::new("timeout", IacType::Integer)
                .default_value(serde_json::json!(30))
                .build(),
        );

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("default-verification"));
        assert!(artifacts[0].content.contains("eq 30"));
    }

    // ---- generate_data_source ----

    #[test]
    fn generate_data_source_produces_two_artifacts() {
        let b = backend();
        let p = provider();
        let ds = test_data_source("config");

        let artifacts = b.generate_data_source(&ds, &p).expect("generate");
        assert_eq!(artifacts.len(), 2);
        assert_eq!(artifacts[0].kind, ArtifactKind::Test);
        assert_eq!(artifacts[1].kind, ArtifactKind::Test);
    }

    #[test]
    fn generate_data_source_inspec_path() {
        let b = backend();
        let p = provider();
        let ds = test_data_source("config");

        let artifacts = b.generate_data_source(&ds, &p).expect("generate");
        assert_eq!(
            artifacts[0].path,
            "profiles/config/controls/config.rb"
        );
    }

    #[test]
    fn generate_data_source_has_existence() {
        let b = backend();
        let p = provider();
        let ds = test_data_source("config");

        let artifacts = b.generate_data_source(&ds, &p).expect("generate");
        assert!(artifacts[0].content.contains("should exist"));
    }

    // ---- generate_provider ----

    #[test]
    fn generate_provider_produces_metadata() {
        let b = backend();
        let p = provider();
        let resources = vec![test_resource("secret")];

        let artifacts = b
            .generate_provider(&p, &resources, &[])
            .expect("generate");
        assert_eq!(artifacts.len(), 1);
        assert_eq!(artifacts[0].kind, ArtifactKind::Metadata);
        assert_eq!(artifacts[0].path, "inspec.yml");
    }

    #[test]
    fn generate_provider_yml_content() {
        let b = backend();
        let p = provider();
        let resources = vec![test_resource("secret")];

        let artifacts = b
            .generate_provider(&p, &resources, &[])
            .expect("generate");
        let yml = &artifacts[0].content;
        assert!(yml.contains("name: akeyless-compliance"));
        assert!(yml.contains("platform: akeyless"));
        assert!(yml.contains("# Resources:"));
        assert!(yml.contains("- secret"));
    }

    #[test]
    fn generate_provider_empty() {
        let b = backend();
        let p = provider();

        let artifacts = b.generate_provider(&p, &[], &[]).expect("generate");
        assert_eq!(artifacts.len(), 1);
        assert!(artifacts[0].content.contains("name: akeyless-compliance"));
    }

    // ---- generate_test ----

    #[test]
    fn generate_test_returns_empty() {
        let b = backend();
        let p = provider();
        let r = test_resource("secret");

        let artifacts = b.generate_test(&r, &p).expect("generate");
        assert!(artifacts.is_empty());
    }

    // ---- generate_all ----

    #[test]
    fn generate_all_artifact_count() {
        let b = backend();
        let p = provider();
        let resources = vec![test_resource("secret"), test_resource("key")];
        let data_sources = vec![test_data_source("config")];

        let artifacts = b
            .generate_all(&p, &resources, &data_sources)
            .expect("generate_all");

        // 2 resources * 2 (inspec + rspec) = 4
        // 1 data source * 2 (inspec + rspec) = 2
        // 1 provider metadata = 1
        // Total = 7
        assert_eq!(artifacts.len(), 7);
    }

    #[test]
    fn generate_all_includes_metadata() {
        let b = backend();
        let p = provider();
        let resources = vec![test_resource("secret")];

        let artifacts = b
            .generate_all(&p, &resources, &[])
            .expect("generate_all");

        assert!(artifacts.iter().any(|a| a.kind == ArtifactKind::Metadata));
    }

    #[test]
    fn generate_all_includes_test_artifacts() {
        let b = backend();
        let p = provider();
        let resources = vec![test_resource("secret")];

        let artifacts = b
            .generate_all(&p, &resources, &[])
            .expect("generate_all");

        let test_count = artifacts.iter().filter(|a| a.kind == ArtifactKind::Test).count();
        assert_eq!(test_count, 2);
    }

    // ---- validate_resource ----

    #[test]
    fn validate_resource_ok() {
        let b = backend();
        let p = provider();
        let r = test_resource("secret");

        let errors = b.validate_resource(&r, &p);
        assert!(errors.is_empty());
    }

    #[test]
    fn validate_resource_empty_attrs() {
        let b = backend();
        let p = provider();
        let mut r = test_resource("empty");
        r.attributes.clear();

        let errors = b.validate_resource(&r, &p);
        assert_eq!(errors.len(), 1);
        assert!(errors[0].contains("no attributes"));
    }

    // ---- with_config ----

    #[test]
    fn with_config_custom_impact() {
        let config = ComplianceConfig {
            impact: crate::config::ImpactLevels {
                existence: 0.9,
                ..Default::default()
            },
            baseline: "custom".to_string(),
        };
        let b = ComplianceBackend::with_config(config);
        let p = provider();
        let r = test_resource("secret");

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("impact 0.9"));
    }

    // ---- default trait ----

    #[test]
    fn default_backend() {
        let b = ComplianceBackend::default();
        assert_eq!(b.platform(), "compliance");
    }

    // ---- type-specific generation ----

    #[test]
    fn generate_resource_with_integer_type() {
        let b = backend();
        let p = provider();
        let r = test_resource_with_type("counter", "count", IacType::Integer);

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("be_a(Integer)"));
    }

    #[test]
    fn generate_resource_with_float_type() {
        let b = backend();
        let p = provider();
        let r = test_resource_with_type("metric", "value", IacType::Float);

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("be_a(Float)"));
    }

    #[test]
    fn generate_resource_with_boolean_type() {
        let b = backend();
        let p = provider();
        let r = test_resource_with_type("flag", "enabled", IacType::Boolean);

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("satisfy"));
    }

    #[test]
    fn generate_resource_with_list_type() {
        let b = backend();
        let p = provider();
        let r = test_resource_with_type(
            "tagged",
            "tags",
            IacType::List(Box::new(IacType::String)),
        );

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("be_an(Array)"));
    }

    #[test]
    fn generate_resource_with_map_type() {
        let b = backend();
        let p = provider();
        let r = test_resource_with_type(
            "config",
            "settings",
            IacType::Map(Box::new(IacType::String)),
        );

        let artifacts = b.generate_resource(&r, &p).expect("generate");
        assert!(artifacts[0].content.contains("be_a(Hash)"));
    }
}
